### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by moorebrb** [suryashekharc/print_schema#1]
Traceback (most recent call last):
  File "/Users/user/Documents/pydys2", line 4, in <module>
    from print_schema import print_schema
  File "/Users/user/Library/Python/2.7/lib/python/site-packages/print_schema/print_schema.py", line 4
    def is_json(obj: str) -> bool:
                   ^
SyntaxError: invalid syntax

**Comment by suryashekharc** [comment]
Hey, thanks for trying this out!
This package uses type-hinting, which is not supported by Python2. Try installing for Python3 using `pip3 install print-schema`?

**Comment by moorebrb** [comment]
That's definitely what the issue was lol. I'm sorry about that, thanks for the help and this awesome tool!
